<a href="https://colab.research.google.com/github/ManjunathAdi/LLMs/blob/main/Introduction_LLMs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Bhagavan Mahamrityunjaya Mahadev

 NOTE: All these notebook work run on Google Colab GPU T4.

# Phi-3

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=True,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

configuration_phi3.py:   0%|          | 0.00/11.2k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_phi3.py:   0%|          | 0.00/73.2k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [9]:
from transformers import pipeline

# Create a pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    return_full_text=False,
    max_new_tokens=800,
    do_sample=False
)

In [10]:
# The prompt (user input / query)
messages = [
    {"role": "user", "content": "Create a funny joke about kapil sharma show"}
]

# Generate output
output = generator(messages)
print(output[0]["generated_text"])

 Why did Kapil Sharma refuse to play hide and seek with his friends?

Because every time he tried to hide, he ended up in the middle of a Kapil Sharma show!


In [12]:
prompt = "Need brief summarization of vedas and upanishads. <|assistant|>"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=800,
  do_sample=True,
  top_p=0.9,
  temperature=1.0,
  repetition_penalty=1.2
)

# Print the output
print(tokenizer.decode(generation_output[0]))

Need brief summarization of vedas and upanishads. <|assistant|> The Vedas are a large body of religious texts originating in ancient India, forming the oldest layer of Sanskrit literature as well as Hinduism's scriptures from around 1500 BCE to about 300 CE; they consist primarily four collections: Rigveda (hymns praising deities), Samaveda ("chants"), Yajurveda(prose mantras associated with rituals)and Atharvaveda("spells for healing"). Each is divided into two parts - mandalas or sections which contain individual hymns known by their titles like Gayatri Mantra).
The Upanishads constitute mainly philosophical speculations based on interpretation through dialogues between teachers/scholars ('guru') & pupils/'shikhis'. They developed out gradually during mid-to late period i e Mahabharata time frame ca Early Modern Period under influence contemporary schools viz Advaita , Visishtadvita etc . It discuss concepts such universality beyond duality eg 'Brahman','Atma'-Self'; nondualistic exi

In [20]:
prompt = "Need brief summarization of vedas and upanishads."

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=16,
  do_sample=True,
  top_p=0.9,
  temperature=1.0,
  repetition_penalty=1.2
)

# Print the output
print(tokenizer.decode(generation_output[0]))

Need brief summarization of vedas and upanishads. Vedas are a large body of religious texts originating in ancient India,


In [21]:
print(input_ids)

tensor([[20768, 11473, 19138,  2133,   310, 11016,   294,   322,   701,   273,
           728,  7925, 29889]], device='cuda:0')


In [22]:
for id in input_ids[0]:
   print(tokenizer.decode(id))

Need
brief
summar
ization
of
ved
as
and
up
an
ish
ads
.


In [31]:
len(input_ids[0])

13

In [23]:
generation_output

tensor([[20768, 11473, 19138,  2133,   310, 11016,   294,   322,   701,   273,
           728,  7925, 29889,   478,   287,   294,   526,   263,  2919,  3573,
           310, 12962, 26442,  3978,  1218,   297, 12297,  7513, 29892]],
       device='cuda:0')

In [32]:
generation_output[0][len(input_ids[0]):]

tensor([  478,   287,   294,   526,   263,  2919,  3573,   310, 12962, 26442,
         3978,  1218,   297, 12297,  7513, 29892], device='cuda:0')

In [33]:
for id in generation_output[0][len(input_ids[0]):]:
   print(tokenizer.decode(id))

V
ed
as
are
a
large
body
of
religious
texts
origin
ating
in
ancient
India
,


# Other Tokenizers

In [35]:
from transformers import AutoModelForCausalLM, AutoTokenizer

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )

In [38]:
text = """
India and NEWDELHI
🎵 鸟
display the tokens False None elif == >= else:  Three tabs: "       "
6.0*80=480
"""

In [47]:
show_tokens(text, "bert-base-uncased")

[CLS] india and new ##del ##hi [UNK] [UNK] display the token ##s false none eli ##f = = > = else : three tab ##s : " " 6 . 0 * 80 = 480 [SEP] 

In [48]:
show_tokens(text, "bert-base-cased")

[CLS] India and NE ##WD ##EL ##H ##I [UNK] [UNK] display the token ##s F ##als ##e None el ##if = = > = else : Three ta ##bs : " " 6 . 0 * 80 = 480 [SEP] 

In [49]:
show_tokens(text, "gpt2")


 India  and  NEW D EL HI 
 � � �  � � � 
 display  the  tokens  False  None  el if  ==  >=  else :    Three  tabs :  "              " 
 6 . 0 * 80 = 480 
 

In [50]:
show_tokens(text, "google/flan-t5-small")

India and NEW D EL HI  <unk>  <unk> display the token s Fal s e None  e l if = = > = else : Three tab s : " "  6.0 * 80 = 480  </s> 

In [51]:
show_tokens(text, "Xenova/gpt-4")


 India  and  NEW DEL HI 
 � � �  � � � 
 display  the  tokens  False  None  elif  ==  >=  else :    Three  tabs :  "         "
 6 . 0 * 80 = 480 
 

In [52]:
show_tokens(text, "bigcode/starcoder2-15b")


 In dia  and  NEW DEL HI 
 � � �   � � 
 display  the  tokens  False  None  elif  ==  >=  else :    Three  tabs :  "         " 
 6 . 0 * 8 0 = 4 8 0 
 

In [53]:
show_tokens(text, "facebook/galactica-1.3b")


 India  and  NE WD EL HI 
 � � � �  � � � 
 display  the  tokens  False  None  elif   ==   > =  else :    Three  t abs :   "         " 
 6 . 0 * 8 0 = 4 8 0 
 

In [54]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

 
 Ind ia and NEW DE L HI 
 � � � �  � � � 
 display the tokens False None elif == >= else :  Three tabs : "       " 
 6 . 0 * 8 0 = 4 8 0 
 

# BERT Word Embeddings

In [55]:
from transformers import AutoModel, AutoTokenizer

# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

# Load a language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

# Tokenize the sentence
tokens = tokenizer('I love Tennis', return_tensors='pt')

# Process the tokens
output = model(**tokens)[0]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/241M [00:00<?, ?B/s]

In [56]:
output.shape

torch.Size([1, 5, 384])

In [57]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
I
 love
 Tennis
[SEP]


In [58]:
output

tensor([[[-3.5066e+00, -1.0607e-03, -1.8394e-01,  ..., -5.8055e-02,
          -2.8014e-01,  4.9697e-02],
         [ 9.3101e-02,  3.1227e-01, -2.0266e-01,  ...,  1.1630e+00,
           3.6791e-01,  8.1730e-01],
         [-7.3735e-01,  2.6077e-01, -9.1381e-02,  ..., -8.3719e-02,
           1.4860e-01,  8.3519e-01],
         [-7.5033e-01,  7.0272e-02, -2.5774e-01,  ..., -8.9773e-01,
          -5.1551e-01,  8.5944e-02],
         [-3.4151e+00,  1.1266e-01, -2.2949e-01,  ..., -1.1063e-01,
          -3.0473e-01,  4.3098e-02]]], grad_fn=<NativeLayerNormBackward0>)

In [61]:
output[0][0].shape, output[0][1].shape, output[0][2].shape, output[0][3].shape, output[0][4].shape

(torch.Size([384]),
 torch.Size([384]),
 torch.Size([384]),
 torch.Size([384]),
 torch.Size([384]))

# Text Embeddings (For Sentences and Whole Documents)

In [64]:
#!pip install sentence-transformers

In [66]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Kedarnath and Badrinath are highly divine, powerful and lovely spiritual places")

In [67]:
vector.shape

(768,)

# Input-Output of trained LLM: Phi-3

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=True,
)

# Create a pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    return_full_text=False,
    max_new_tokens=60,
    do_sample=False,
)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [3]:
prompt = "Explain the horrific killing of Hindus done by muslim kings in India. Explain how it happened."

output = generator(prompt)

print(output[0]['generated_text'])



Muslim rulers in India have been accused of committing horrific acts against Hindus throughout history. These accusations are often based on historical events and conflicts that took place during various periods of Indian history. It is important to approach this topic with sensitivity and an understanding


In [4]:
print(model)

Phi3ForCausalLM(
  (model): Phi3Model(
    (embed_tokens): Embedding(32064, 3072, padding_idx=32000)
    (embed_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-31): 32 x Phi3DecoderLayer(
        (self_attn): Phi3Attention(
          (o_proj): Linear(in_features=3072, out_features=3072, bias=False)
          (qkv_proj): Linear(in_features=3072, out_features=9216, bias=False)
          (rotary_emb): Phi3RotaryEmbedding()
        )
        (mlp): Phi3MLP(
          (gate_up_proj): Linear(in_features=3072, out_features=16384, bias=False)
          (down_proj): Linear(in_features=8192, out_features=3072, bias=False)
          (activation_fn): SiLU()
        )
        (input_layernorm): Phi3RMSNorm()
        (resid_attn_dropout): Dropout(p=0.0, inplace=False)
        (resid_mlp_dropout): Dropout(p=0.0, inplace=False)
        (post_attention_layernorm): Phi3RMSNorm()
      )
    )
    (norm): Phi3RMSNorm()
  )
  (lm_head): Linear(in_features=3072, out_features=3206

# Selecting single token with max probabaility

In [6]:

prompt = "The capital of Japan is"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

# Tokenize the input prompt
input_ids = input_ids.to("cuda")

# Get the output of the model before the lm_head
model_output = model.model(input_ids)

# Get the output of the lm_head
lm_head_output = model.lm_head(model_output[0])

In [12]:
lm_head_output.shape

torch.Size([1, 5, 32064])

In [14]:
lm_head_output[0,-1].argmax(-1)

tensor(20377, device='cuda:0')

In [15]:
token_id = lm_head_output[0,-1].argmax(-1)
tokenizer.decode(token_id)

'Tokyo'

# Usage of use_cache=True/False

In [19]:
prompt = "Write a very long essay on the topic of greatest tennis player of all time"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
input_ids = input_ids.to("cuda")

In [21]:
%%timeit -n 1
# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=80,
  use_cache=True
)

4.31 s ± 713 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
%%timeit -n 1
# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=80,
  use_cache=False
)

22.3 s ± 346 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
